### ISSUE TITLE
[bug] Confirm widget left/right keys handling

### ISSUE THREAD

**Issue by alexeiras** [liamg/flinch#6]
Hey @liamg! 👋 Hope everything is going great!

Just noticed that, in the confirm window, pressing left/right keys will just update the buttons' display. But the actual selected component will still be the one picked upon first render. 

Reproducing it is straight forward. Just run https://github.com/liamg/flinch/blob/main/_examples/confirm/main.go press the right key (the "No" button will be apparently selected) and press Enter. Confirmed: true will be printed out.

Cheers!

**Comment by liamg** [comment]
Thanks, this is fixed in `v0.0.18`
